// TEACHER
export const FETCH_TEACHERS = "FETCH_TEACHERS"

// COMPTE
export const FETCH_COMPTES = "FETCH_COMPTES"
export const ADD_COMPTE = "ADD_COMPTE"
export const UPDATE_COMPTE = "UPDATE_COMPTE"
export const DELETE_COMPTE = "DELETE_COMPTE"
//LOADING
export const START_LOADING = "START_LOADING"
export const END_LOADING = "END_LOADING"

// AUTH
export const AUTH ="AUTH"
export const LOGOUT = "LOGOUT"

//FILIERE
export const FETCH_FILIERES = "FETCH_FILIERES"

//MODULES
export const FETCH_MODULES = "FETCH_MODULES"
export const VALIDATE_MODULE = "VALIDATE_MODULE"

//ELEMENTS 
export const FETCH_ELEMENTS = "FETCH_ELEMENTS"
export const UPDATE_ELEMENTS_TO_PROF = "UPDATE_ELEMENTS_TO_PROF"
export const VALIDATE_ELEMENT = "VALIDATE_ELEMENT"
//STUDENTS
export const FETCH_STUDENTS = "FETCH_STUDENTS"

//NOTES
export  const FETCH_NOTES = "FETCH_NOTES"
export  const UPDATE_NOTE = "UPDATE_NOTE"

//TODOLIST 
export const FETCH_TODOS = "FETCH_TODOS"
export const ADD_TODO = "ADD_TODO"
export const DELETE_TODO = "DELETE_TODO"

export const UPDATE_TODO = "UPDATE_TODO"

//NOTIFICATIONS

export const FETCH_NOTIFICATIONS = "FETCH_NOTIFICATIONS"
export const ADD_NOTIFICATION = "ADD_NOTIFICATION"
export const DELETE_NOTIFICATION = "DELETE_NOTIFICATION"

//EVENTS

export const FETCH_EVENTS = "FETCH_EVENTS"
export const ADD_EVENT = "ADD_EVENT"
export const DELETE_EVENT = "DELETE_EVENT"